version: "3.3"
services:
  proxy:
    depends_on:
      - app
      - admin
      - api
      - phpmyadmin
    build: "./proxy"
    ports:
      - 80:80
    networks:
      - frontend
      - backend
  app:
    build: "./app"
    depends_on:
      - api
    expose:
      - 3000
    volumes:
      - ./app:/app
      - /app/node_modules
    networks:
      - frontend
  admin:
    build: "./admin"
    depends_on:
      - api
    expose:
      - 3000
    volumes:
      - ./admin:/admin
      - /admin/node_modules
    networks:
      - frontend
  api:
    depends_on:
      - db
    build: "./api"
    expose:
      - 5000
    volumes:
      - ./api:/api
      - /api/node_modules
    networks:
      - backend
    env_file:
      - ./api/.env
  db:
    image: mysql:8.0.26
    expose:
      - 3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=webshop_db
      - MYSQL_USER=hoaideptrai
      - MYSQL_PASSWORD=123456
    cap_add:
      - CAP_SYS_NICE
  db-test:
    image: mysql:8.0.26
    expose:
      - 3306
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=webshop_db
      - MYSQL_USER=hoaideptrai
      - MYSQL_PASSWORD=123456
    cap_add:
      - CAP_SYS_NICE
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    networks:
      - backend
    expose:
      - 80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
volumes:
  db-data:
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
