version: "3.3"
services:
  proxy:
    depends_on:
      - app
      - admin
      - api
    build:
      context: ./proxy
      dockerfile: Dockerfile.deploy
    restart: always
    ports:
      - 80:80
    networks:
      - frontend
      - backend
    environment:
      - APP_SERVER_NAME=app.webshopbeta.cf
      - APP_SERVER_URI=http://app:3000
      - ADMIN_SERVER_NAME=admin.webshopbeta.cf
      - ADMIN_SERVER_URI=http://admin:3000
      - API_SERVER_NAME=api.webshopbeta.cf
      - API_SERVER_URI=http://api:5000
  app:
    image: harbor.zinza.com.vn/hoaihv/webshop/webshop_app:latest
    depends_on:
      - api
    restart: always
    expose:
      - 3000
    volumes:
      - ./app:/app
      - /app/node_modules
    networks:
      - frontend
    environment:
      - NODE_ENV=production
      - REACT_APP_API_BASE=http://api.webshopbeta.cf
  admin:
    image: harbor.zinza.com.vn/hoaihv/webshop/webshop_admin:latest
    depends_on:
      - api
    restart: always
    expose:
      - 3000
    volumes:
      - ./admin:/admin
      - /admin/node_modules
    networks:
      - frontend
    environment:
      - NODE_ENV=production
      - REACT_APP_API_BASE=http://api.webshopbeta.cf
      - REACT_APP_APP_BASE=http://webshopbeta.cf
      - REACT_APP_FIREBASE_API_KEY=AIzaSyDqoLUYQhW7NlH57EfBO63D4KRqi3IgE78
      - REACT_APP_FIREBASE_AUTH_DOMAIN=webshop-e2f76.firebaseapp.com
      - REACT_APP_FIREBASE_PROJECT_ID=webshop-e2f76
      - REACT_APP_FIREBASE_STORAGE_BUCKET=webshop-e2f76.appspot.com
      - REACT_APP_FIREBASE_MESSAGING_SENDER_ID=1057783220542
      - REACT_APP_FIREBASE_APP_ID=1:1057783220542:web:14904508fb92f27adcc46f
      - REACT_APP_FIREBASE_MEASUREMENT_ID=G-BC1C3M52TZ
  api:
    image: harbor.zinza.com.vn/hoaihv/webshop/webshop_api:latest
    depends_on:
      - db
    restart: always
    expose:
      - 5000
    volumes:
      - ./api:/api
      - /api/node_modules
    networks:
      - backend
    env_file:
      - ./api/.env
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=db
      - DB_NAME=webshop_db
      - DB_USERNAME=hoaideptrai
      - DB_PASSWORD=123456
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=123456
      - APP_BASE=http://webshopbeta.cf
      - ADMIN_BASE=http://admin.webshopbeta.cf
      - JWT_ACCESS_TOKEN_SECRET=Ysg$fG&DG
      - JWT_REFRESH_TOKEN_SECRET=Txlcvkb^32y
  worker:
    depends_on:
      - api
    build: "./worker"
    expose:
      - 5000
    volumes:
      - ./worker:/worker
      - /worker/node_modules
    networks:
      - backend
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=123456
  db:
    image: mysql:8.0.26
    restart: always
    expose:
      - 3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=webshop_db
      - MYSQL_USER=hoaideptrai
      - MYSQL_PASSWORD=123456
    cap_add:
      - CAP_SYS_NICE
  redis:
    # remember to SET PASSWORD below
    command: "redis-server --requirepass 123456 --maxmemory-policy noeviction"
    image: redis:6.2.5-alpine
    expose:
      - 6379
    networks:
      - backend
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  db-data:
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
