version: "3.3"
services:
 backend:
  depends_on:
   - db
  build: './webshop-api'
  expose:
   - 5000
  volumes:
   - ./webshop-api:/api
   - /api/node_modules
  networks:
   - proxy_backend
   - database_backend
  env_file:
   - ./webshop-api/.env
 frontend:
  build: './webshop-app'
  expose:
   - 3000
  volumes:
   - ./webshop-app:/app
   - /app/node_modules
  networks:
   - proxy_frontend
 proxy:
  depends_on:
   - frontend
   - backend
  build: './proxy'
  ports:
   - 80:80
  networks:
   - proxy_frontend
   - proxy_backend
 db:
  image: mysql:8.0.26
  expose:
   - 3306
  volumes:
   - db-data:/var/lib/mysql
  networks:
   - database_backend
  environment:
   - MYSQL_ROOT_PASSWORD=123456
   - MYSQL_DATABASE=webshop_db
   - MYSQL_USER=hoaideptrai
   - MYSQL_PASSWORD=123456
  cap_add:
   - CAP_SYS_NICE
volumes:
 db-data:
networks:
 proxy_backend:
  driver: bridge
 proxy_frontend:
  driver: bridge
 database_backend:
  driver: bridge
