import { SAMPLE_PRODUCT as sampleProduct } from '../../../constants';

describe('product page: quantity selector', () => {
	beforeEach(() => {
		cy.gotoSampleProduct();
	})
	it('visible and have default value 1', () => {
		cy
			.get('div[id="select-area"]')
			.react('QuantitySelector')
			.should('be.visible')
			.react('TextField')
			.getReact('InputBase')
			.getProps('value')
			.should('eq', 1)
	})
	it('can clear', () => {
		cy.get('div#select-area')
			.react('QuantitySelector')
			.react('InputBase')
			.find('input')
			.clear()
		cy.get('div#select-area')
			.react('QuantitySelector')
			.getReact('InputBase')
			.getProps('value')
			.should('eq', '')
	})
	it('with input < 1', () => {
		cy.get('div#select-area')
			.react('QuantitySelector')
			.react('InputBase')
			.find('input')
			.clear()
			.type(0)
		cy.get('div#select-area')
			.react('QuantitySelector')
			.getReact('InputBase')
			.getProps('value')
			.should('eq', 1)
	})
	it('with input = 1', () => {
		cy.get('div#select-area')
			.react('QuantitySelector')
			.react('InputBase')
			.find('input')
			.clear()
			.type(1)
		cy.get('div#select-area')
			.react('QuantitySelector')
			.getReact('InputBase')
			.getProps('value')
			.should('eq', 1)
	})
	it('with input 1 <= x <= productQuantity', () => {
		const x = Math.floor(Math.random() * sampleProduct.quantity) + 1;
		cy.get('div#select-area')
			.react('QuantitySelector')
			.react('InputBase')
			.find('input')
			.clear()
			.type(x)
		cy.get('div#select-area')
			.react('QuantitySelector')
			.getReact('InputBase')
			.getProps('value')
			.should('eq', x)
	})
	it('with input x > productQuantity', () => {
		const x = sampleProduct.quantity + 1;
		cy.get('div#select-area')
			.react('QuantitySelector')
			.react('InputBase')
			.find('input')
			.clear()
			.type(x)
		cy.get('div#select-area')
			.react('QuantitySelector')
			.getReact('InputBase')
			.getProps('value')
			.should('be.lessThan', x)
	})
})